// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: model_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamModelsRequest) Reset() {
	*x = StreamModelsRequest{}
	mi := &file_model_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamModelsRequest) ProtoMessage() {}

func (x *StreamModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamModelsRequest.ProtoReflect.Descriptor instead.
func (*StreamModelsRequest) Descriptor() ([]byte, []int) {
	return file_model_service_proto_rawDescGZIP(), []int{0}
}

type ModelUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelData     []byte                 `protobuf:"bytes,1,opt,name=model_data,json=modelData,proto3" json:"model_data,omitempty"`                // Serialized TPackModels protobuf
	TrainedAtUnix int64                  `protobuf:"varint,2,opt,name=trained_at_unix,json=trainedAtUnix,proto3" json:"trained_at_unix,omitempty"` // Unix timestamp when training completed
	TraceCount    int32                  `protobuf:"varint,3,opt,name=trace_count,json=traceCount,proto3" json:"trace_count,omitempty"`            // Number of traces used in this training batch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelUpdate) Reset() {
	*x = ModelUpdate{}
	mi := &file_model_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelUpdate) ProtoMessage() {}

func (x *ModelUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_model_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelUpdate.ProtoReflect.Descriptor instead.
func (*ModelUpdate) Descriptor() ([]byte, []int) {
	return file_model_service_proto_rawDescGZIP(), []int{1}
}

func (x *ModelUpdate) GetModelData() []byte {
	if x != nil {
		return x.ModelData
	}
	return nil
}

func (x *ModelUpdate) GetTrainedAtUnix() int64 {
	if x != nil {
		return x.TrainedAtUnix
	}
	return 0
}

func (x *ModelUpdate) GetTraceCount() int32 {
	if x != nil {
		return x.TraceCount
	}
	return 0
}

var File_model_service_proto protoreflect.FileDescriptor

const file_model_service_proto_rawDesc = "" +
	"\n" +
	"\x13model_service.proto\x12\x05tpack\"\x15\n" +
	"\x13StreamModelsRequest\"u\n" +
	"\vModelUpdate\x12\x1d\n" +
	"\n" +
	"model_data\x18\x01 \x01(\fR\tmodelData\x12&\n" +
	"\x0ftrained_at_unix\x18\x02 \x01(\x03R\rtrainedAtUnix\x12\x1f\n" +
	"\vtrace_count\x18\x03 \x01(\x05R\n" +
	"traceCount2P\n" +
	"\fModelService\x12@\n" +
	"\fStreamModels\x12\x1a.tpack.StreamModelsRequest\x1a\x12.tpack.ModelUpdate0\x01B3Z1github.com/ProjectASAP/TPack/pkg/tpackmodel/protob\x06proto3"

var (
	file_model_service_proto_rawDescOnce sync.Once
	file_model_service_proto_rawDescData []byte
)

func file_model_service_proto_rawDescGZIP() []byte {
	file_model_service_proto_rawDescOnce.Do(func() {
		file_model_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_service_proto_rawDesc), len(file_model_service_proto_rawDesc)))
	})
	return file_model_service_proto_rawDescData
}

var file_model_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_model_service_proto_goTypes = []any{
	(*StreamModelsRequest)(nil), // 0: tpack.StreamModelsRequest
	(*ModelUpdate)(nil),         // 1: tpack.ModelUpdate
}
var file_model_service_proto_depIdxs = []int32{
	0, // 0: tpack.ModelService.StreamModels:input_type -> tpack.StreamModelsRequest
	1, // 1: tpack.ModelService.StreamModels:output_type -> tpack.ModelUpdate
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_model_service_proto_init() }
func file_model_service_proto_init() {
	if File_model_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_service_proto_rawDesc), len(file_model_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_model_service_proto_goTypes,
		DependencyIndexes: file_model_service_proto_depIdxs,
		MessageInfos:      file_model_service_proto_msgTypes,
	}.Build()
	File_model_service_proto = out.File
	file_model_service_proto_goTypes = nil
	file_model_service_proto_depIdxs = nil
}
