// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: tpack.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Trace type for stratified sampling
type TraceType int32

const (
	TraceType_NORMAL TraceType = 0 // Normal trace (no ERROR spans)
	TraceType_ERROR  TraceType = 1 // Error trace (contains at least one span with status.code=2)
)

// Enum value maps for TraceType.
var (
	TraceType_name = map[int32]string{
		0: "NORMAL",
		1: "ERROR",
	}
	TraceType_value = map[string]int32{
		"NORMAL": 0,
		"ERROR":  1,
	}
)

func (x TraceType) Enum() *TraceType {
	p := new(TraceType)
	*p = x
	return p
}

func (x TraceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TraceType) Descriptor() protoreflect.EnumDescriptor {
	return file_tpack_proto_enumTypes[0].Descriptor()
}

func (TraceType) Type() protoreflect.EnumType {
	return &file_tpack_proto_enumTypes[0]
}

func (x TraceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TraceType.Descriptor instead.
func (TraceType) EnumDescriptor() ([]byte, []int) {
	return file_tpack_proto_rawDescGZIP(), []int{0}
}

// Main message containing all TPack models
type TPackModels struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Node vocabulary for cross-language compat
	NodeVocabulary []string `protobuf:"bytes,1,rep,name=node_vocabulary,json=nodeVocabulary,proto3" json:"node_vocabulary,omitempty"`
	// Embedded config for self-describing archives
	Config *TPackConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	// Timing metadata from training batch (for pacing trace emission)
	MinStartTimeUs int64 `protobuf:"varint,3,opt,name=min_start_time_us,json=minStartTimeUs,proto3" json:"min_start_time_us,omitempty"`
	MaxStartTimeUs int64 `protobuf:"varint,4,opt,name=max_start_time_us,json=maxStartTimeUs,proto3" json:"max_start_time_us,omitempty"`
	TraceCount     int32 `protobuf:"varint,5,opt,name=trace_count,json=traceCount,proto3" json:"trace_count,omitempty"`
	// Models
	MaxNodesCount                  int32                                 `protobuf:"varint,6,opt,name=max_nodes_count,json=maxNodesCount,proto3" json:"max_nodes_count,omitempty"`
	RootModels                     []*RootCountModel                     `protobuf:"bytes,7,rep,name=root_models,json=rootModels,proto3" json:"root_models,omitempty"`
	TopologyModels                 []*TopologyModel                      `protobuf:"bytes,8,rep,name=topology_models,json=topologyModels,proto3" json:"topology_models,omitempty"`
	RootDurationModels             []*RootDurationModel                  `protobuf:"bytes,9,rep,name=root_duration_models,json=rootDurationModels,proto3" json:"root_duration_models,omitempty"`
	SpanDurationBounds             []*SpanDurationBounds                 `protobuf:"bytes,10,rep,name=span_duration_bounds,json=spanDurationBounds,proto3" json:"span_duration_bounds,omitempty"`
	SpanGapBounds                  []*SpanGapBounds                      `protobuf:"bytes,11,rep,name=span_gap_bounds,json=spanGapBounds,proto3" json:"span_gap_bounds,omitempty"`
	StatisticalDependentAttributes []*StatisticalDependentAttributeModel `protobuf:"bytes,12,rep,name=statistical_dependent_attributes,json=statisticalDependentAttributes,proto3" json:"statistical_dependent_attributes,omitempty"`
	// Dynamic dependent attributes (e.g. ["http.status_code"])
	DependentAttributes      []string                   `protobuf:"bytes,13,rep,name=dependent_attributes,json=dependentAttributes,proto3" json:"dependent_attributes,omitempty"`
	DependentAttributeVocabs []*DependentAttributeVocab `protobuf:"bytes,14,rep,name=dependent_attribute_vocabs,json=dependentAttributeVocabs,proto3" json:"dependent_attribute_vocabs,omitempty"`
	// Primary attributes that form node identity (e.g. ["service.name", "span.kind", ...])
	PrimaryAttributes []string `protobuf:"bytes,15,rep,name=primary_attributes,json=primaryAttributes,proto3" json:"primary_attributes,omitempty"`
	// Delta vocabulary encoding: cumulative vocab size after this bucket's entries.
	// == 0: legacy mode, node_vocabulary is the full vocabulary.
	// > 0: delta mode, node_vocabulary contains only new entries at indices
	//
	//	[cumulative_vocab_size - len(node_vocabulary), cumulative_vocab_size).
	CumulativeVocabSize int32 `protobuf:"varint,16,opt,name=cumulative_vocab_size,json=cumulativeVocabSize,proto3" json:"cumulative_vocab_size,omitempty"`
	// Trace templates (used when topology_mode = "template")
	TraceTemplates []*TraceTemplateProto `protobuf:"bytes,17,rep,name=trace_templates,json=traceTemplates,proto3" json:"trace_templates,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TPackModels) Reset() {
	*x = TPackModels{}
	mi := &file_tpack_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TPackModels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TPackModels) ProtoMessage() {}

func (x *TPackModels) ProtoReflect() protoreflect.Message {
	mi := &file_tpack_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TPackModels.ProtoReflect.Descriptor instead.
func (*TPackModels) Descriptor() ([]byte, []int) {
	return file_tpack_proto_rawDescGZIP(), []int{0}
}

func (x *TPackModels) GetNodeVocabulary() []string {
	if x != nil {
		return x.NodeVocabulary
	}
	return nil
}

func (x *TPackModels) GetConfig() *TPackConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *TPackModels) GetMinStartTimeUs() int64 {
	if x != nil {
		return x.MinStartTimeUs
	}
	return 0
}

func (x *TPackModels) GetMaxStartTimeUs() int64 {
	if x != nil {
		return x.MaxStartTimeUs
	}
	return 0
}

func (x *TPackModels) GetTraceCount() int32 {
	if x != nil {
		return x.TraceCount
	}
	return 0
}

func (x *TPackModels) GetMaxNodesCount() int32 {
	if x != nil {
		return x.MaxNodesCount
	}
	return 0
}

func (x *TPackModels) GetRootModels() []*RootCountModel {
	if x != nil {
		return x.RootModels
	}
	return nil
}

func (x *TPackModels) GetTopologyModels() []*TopologyModel {
	if x != nil {
		return x.TopologyModels
	}
	return nil
}

func (x *TPackModels) GetRootDurationModels() []*RootDurationModel {
	if x != nil {
		return x.RootDurationModels
	}
	return nil
}

func (x *TPackModels) GetSpanDurationBounds() []*SpanDurationBounds {
	if x != nil {
		return x.SpanDurationBounds
	}
	return nil
}

func (x *TPackModels) GetSpanGapBounds() []*SpanGapBounds {
	if x != nil {
		return x.SpanGapBounds
	}
	return nil
}

func (x *TPackModels) GetStatisticalDependentAttributes() []*StatisticalDependentAttributeModel {
	if x != nil {
		return x.StatisticalDependentAttributes
	}
	return nil
}

func (x *TPackModels) GetDependentAttributes() []string {
	if x != nil {
		return x.DependentAttributes
	}
	return nil
}

func (x *TPackModels) GetDependentAttributeVocabs() []*DependentAttributeVocab {
	if x != nil {
		return x.DependentAttributeVocabs
	}
	return nil
}

func (x *TPackModels) GetPrimaryAttributes() []string {
	if x != nil {
		return x.PrimaryAttributes
	}
	return nil
}

func (x *TPackModels) GetCumulativeVocabSize() int32 {
	if x != nil {
		return x.CumulativeVocabSize
	}
	return 0
}

func (x *TPackModels) GetTraceTemplates() []*TraceTemplateProto {
	if x != nil {
		return x.TraceTemplates
	}
	return nil
}

// Per-column vocabulary for a dynamic dependent attribute.
type DependentAttributeVocab struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColumnName    string                 `protobuf:"bytes,1,opt,name=column_name,json=columnName,proto3" json:"column_name,omitempty"`
	Values        []string               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DependentAttributeVocab) Reset() {
	*x = DependentAttributeVocab{}
	mi := &file_tpack_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DependentAttributeVocab) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependentAttributeVocab) ProtoMessage() {}

func (x *DependentAttributeVocab) ProtoReflect() protoreflect.Message {
	mi := &file_tpack_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependentAttributeVocab.ProtoReflect.Descriptor instead.
func (*DependentAttributeVocab) Descriptor() ([]byte, []int) {
	return file_tpack_proto_rawDescGZIP(), []int{1}
}

func (x *DependentAttributeVocab) GetColumnName() string {
	if x != nil {
		return x.ColumnName
	}
	return ""
}

func (x *DependentAttributeVocab) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// Configuration for TPack algorithm
type TPackConfig struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	MaxDepth                  int32                  `protobuf:"varint,1,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`
	MaxChildren               int32                  `protobuf:"varint,2,opt,name=max_children,json=maxChildren,proto3" json:"max_children,omitempty"`
	MaxGmmComponents          int32                  `protobuf:"varint,3,opt,name=max_gmm_components,json=maxGmmComponents,proto3" json:"max_gmm_components,omitempty"`
	MinSamplesForGmm          int32                  `protobuf:"varint,4,opt,name=min_samples_for_gmm,json=minSamplesForGmm,proto3" json:"min_samples_for_gmm,omitempty"`
	RejectSamplingMaxAttempts int32                  `protobuf:"varint,5,opt,name=reject_sampling_max_attempts,json=rejectSamplingMaxAttempts,proto3" json:"reject_sampling_max_attempts,omitempty"`
	RejectSamplingEnabled     bool                   `protobuf:"varint,6,opt,name=reject_sampling_enabled,json=rejectSamplingEnabled,proto3" json:"reject_sampling_enabled,omitempty"`
	StratifiedSampling        bool                   `protobuf:"varint,7,opt,name=stratified_sampling,json=stratifiedSampling,proto3" json:"stratified_sampling,omitempty"`
	RandomSeed                int32                  `protobuf:"varint,8,opt,name=random_seed,json=randomSeed,proto3" json:"random_seed,omitempty"`
	OffsetValue               string                 `protobuf:"bytes,9,opt,name=offset_value,json=offsetValue,proto3" json:"offset_value,omitempty"`                       // "ratio" or "absolute"
	OffsetModel               string                 `protobuf:"bytes,10,opt,name=offset_model,json=offsetModel,proto3" json:"offset_model,omitempty"`                      // "regression" or "percentile"
	UseDurationBounds         bool                   `protobuf:"varint,11,opt,name=use_duration_bounds,json=useDurationBounds,proto3" json:"use_duration_bounds,omitempty"` // Clamp generated durations/gaps to observed bounds
	TopologyMode              string                 `protobuf:"bytes,12,opt,name=topology_mode,json=topologyMode,proto3" json:"topology_mode,omitempty"`                   // "edge" (default) or "template"
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *TPackConfig) Reset() {
	*x = TPackConfig{}
	mi := &file_tpack_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TPackConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TPackConfig) ProtoMessage() {}

func (x *TPackConfig) ProtoReflect() protoreflect.Message {
	mi := &file_tpack_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TPackConfig.ProtoReflect.Descriptor instead.
func (*TPackConfig) Descriptor() ([]byte, []int) {
	return file_tpack_proto_rawDescGZIP(), []int{2}
}

func (x *TPackConfig) GetMaxDepth() int32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

func (x *TPackConfig) GetMaxChildren() int32 {
	if x != nil {
		return x.MaxChildren
	}
	return 0
}

func (x *TPackConfig) GetMaxGmmComponents() int32 {
	if x != nil {
		return x.MaxGmmComponents
	}
	return 0
}

func (x *TPackConfig) GetMinSamplesForGmm() int32 {
	if x != nil {
		return x.MinSamplesForGmm
	}
	return 0
}

func (x *TPackConfig) GetRejectSamplingMaxAttempts() int32 {
	if x != nil {
		return x.RejectSamplingMaxAttempts
	}
	return 0
}

func (x *TPackConfig) GetRejectSamplingEnabled() bool {
	if x != nil {
		return x.RejectSamplingEnabled
	}
	return false
}

func (x *TPackConfig) GetStratifiedSampling() bool {
	if x != nil {
		return x.StratifiedSampling
	}
	return false
}

func (x *TPackConfig) GetRandomSeed() int32 {
	if x != nil {
		return x.RandomSeed
	}
	return 0
}

func (x *TPackConfig) GetOffsetValue() string {
	if x != nil {
		return x.OffsetValue
	}
	return ""
}

func (x *TPackConfig) GetOffsetModel() string {
	if x != nil {
		return x.OffsetModel
	}
	return ""
}

func (x *TPackConfig) GetUseDurationBounds() bool {
	if x != nil {
		return x.UseDurationBounds
	}
	return false
}

func (x *TPackConfig) GetTopologyMode() string {
	if x != nil {
		return x.TopologyMode
	}
	return ""
}

// Node feature representation
type NodeFeature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeIdx       int32                  `protobuf:"varint,1,opt,name=node_idx,json=nodeIdx,proto3" json:"node_idx,omitempty"`          // Index into the shared node encoder vocabulary
	ChildIdx      int32                  `protobuf:"varint,2,opt,name=child_idx,json=childIdx,proto3" json:"child_idx,omitempty"`       // Index of this node among its parent's children (sorted by startTime)
	ChildCount    int32                  `protobuf:"varint,3,opt,name=child_count,json=childCount,proto3" json:"child_count,omitempty"` // Number of children this node has
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeFeature) Reset() {
	*x = NodeFeature{}
	mi := &file_tpack_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeFeature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeFeature) ProtoMessage() {}

func (x *NodeFeature) ProtoReflect() protoreflect.Message {
	mi := &file_tpack_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeFeature.ProtoReflect.Descriptor instead.
func (*NodeFeature) Descriptor() ([]byte, []int) {
	return file_tpack_proto_rawDescGZIP(), []int{3}
}

func (x *NodeFeature) GetNodeIdx() int32 {
	if x != nil {
		return x.NodeIdx
	}
	return 0
}

func (x *NodeFeature) GetChildIdx() int32 {
	if x != nil {
		return x.ChildIdx
	}
	return 0
}

func (x *NodeFeature) GetChildCount() int32 {
	if x != nil {
		return x.ChildCount
	}
	return 0
}

// Root count model: maps node feature to occurrence count
type RootCountModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feature       *NodeFeature           `protobuf:"bytes,1,opt,name=feature,proto3" json:"feature,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	TraceType     TraceType              `protobuf:"varint,3,opt,name=trace_type,json=traceType,proto3,enum=tpack.TraceType" json:"trace_type,omitempty"` // Normal or Error trace
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootCountModel) Reset() {
	*x = RootCountModel{}
	mi := &file_tpack_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootCountModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootCountModel) ProtoMessage() {}

func (x *RootCountModel) ProtoReflect() protoreflect.Message {
	mi := &file_tpack_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootCountModel.ProtoReflect.Descriptor instead.
func (*RootCountModel) Descriptor() ([]byte, []int) {
	return file_tpack_proto_rawDescGZIP(), []int{4}
}

func (x *RootCountModel) GetFeature() *NodeFeature {
	if x != nil {
		return x.Feature
	}
	return nil
}

func (x *RootCountModel) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *RootCountModel) GetTraceType() TraceType {
	if x != nil {
		return x.TraceType
	}
	return TraceType_NORMAL
}

// Topology model: maps parent-child feature pair to edge count
type TopologyModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentFeature *NodeFeature           `protobuf:"bytes,1,opt,name=parent_feature,json=parentFeature,proto3" json:"parent_feature,omitempty"`
	ChildFeature  *NodeFeature           `protobuf:"bytes,2,opt,name=child_feature,json=childFeature,proto3" json:"child_feature,omitempty"`
	Count         uint64                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	TraceType     TraceType              `protobuf:"varint,4,opt,name=trace_type,json=traceType,proto3,enum=tpack.TraceType" json:"trace_type,omitempty"` // Normal or Error trace
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopologyModel) Reset() {
	*x = TopologyModel{}
	mi := &file_tpack_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyModel) ProtoMessage() {}

func (x *TopologyModel) ProtoReflect() protoreflect.Message {
	mi := &file_tpack_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyModel.ProtoReflect.Descriptor instead.
func (*TopologyModel) Descriptor() ([]byte, []int) {
	return file_tpack_proto_rawDescGZIP(), []int{5}
}

func (x *TopologyModel) GetParentFeature() *NodeFeature {
	if x != nil {
		return x.ParentFeature
	}
	return nil
}

func (x *TopologyModel) GetChildFeature() *NodeFeature {
	if x != nil {
		return x.ChildFeature
	}
	return nil
}

func (x *TopologyModel) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *TopologyModel) GetTraceType() TraceType {
	if x != nil {
		return x.TraceType
	}
	return TraceType_NORMAL
}

// Root duration model: maps node feature to Gaussian mixture
type RootDurationModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feature       *NodeFeature           `protobuf:"bytes,1,opt,name=feature,proto3" json:"feature,omitempty"`
	Distribution  *GaussianMixtureParams `protobuf:"bytes,2,opt,name=distribution,proto3" json:"distribution,omitempty"`
	MinDuration   float64                `protobuf:"fixed64,3,opt,name=min_duration,json=minDuration,proto3" json:"min_duration,omitempty"` // Original minimum duration for bounds checking
	MaxDuration   float64                `protobuf:"fixed64,4,opt,name=max_duration,json=maxDuration,proto3" json:"max_duration,omitempty"` // Original maximum duration for bounds checking
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootDurationModel) Reset() {
	*x = RootDurationModel{}
	mi := &file_tpack_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootDurationModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootDurationModel) ProtoMessage() {}

func (x *RootDurationModel) ProtoReflect() protoreflect.Message {
	mi := &file_tpack_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootDurationModel.ProtoReflect.Descriptor instead.
func (*RootDurationModel) Descriptor() ([]byte, []int) {
	return file_tpack_proto_rawDescGZIP(), []int{6}
}

func (x *RootDurationModel) GetFeature() *NodeFeature {
	if x != nil {
		return x.Feature
	}
	return nil
}

func (x *RootDurationModel) GetDistribution() *GaussianMixtureParams {
	if x != nil {
		return x.Distribution
	}
	return nil
}

func (x *RootDurationModel) GetMinDuration() float64 {
	if x != nil {
		return x.MinDuration
	}
	return 0
}

func (x *RootDurationModel) GetMaxDuration() float64 {
	if x != nil {
		return x.MaxDuration
	}
	return 0
}

// Span duration bounds: maps node feature to min/max duration bounds
type SpanDurationBounds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feature       *NodeFeature           `protobuf:"bytes,1,opt,name=feature,proto3" json:"feature,omitempty"`
	MinDuration   float64                `protobuf:"fixed64,2,opt,name=min_duration,json=minDuration,proto3" json:"min_duration,omitempty"` // Minimum duration observed for this feature
	MaxDuration   float64                `protobuf:"fixed64,3,opt,name=max_duration,json=maxDuration,proto3" json:"max_duration,omitempty"` // Maximum duration observed for this feature
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpanDurationBounds) Reset() {
	*x = SpanDurationBounds{}
	mi := &file_tpack_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpanDurationBounds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpanDurationBounds) ProtoMessage() {}

func (x *SpanDurationBounds) ProtoReflect() protoreflect.Message {
	mi := &file_tpack_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpanDurationBounds.ProtoReflect.Descriptor instead.
func (*SpanDurationBounds) Descriptor() ([]byte, []int) {
	return file_tpack_proto_rawDescGZIP(), []int{7}
}

func (x *SpanDurationBounds) GetFeature() *NodeFeature {
	if x != nil {
		return x.Feature
	}
	return nil
}

func (x *SpanDurationBounds) GetMinDuration() float64 {
	if x != nil {
		return x.MinDuration
	}
	return 0
}

func (x *SpanDurationBounds) GetMaxDuration() float64 {
	if x != nil {
		return x.MaxDuration
	}
	return 0
}

// Span gap bounds: maps node feature to min/max gap_from_parent bounds
type SpanGapBounds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feature       *NodeFeature           `protobuf:"bytes,1,opt,name=feature,proto3" json:"feature,omitempty"`
	MinGap        float64                `protobuf:"fixed64,2,opt,name=min_gap,json=minGap,proto3" json:"min_gap,omitempty"` // Minimum gap_from_parent observed for this feature
	MaxGap        float64                `protobuf:"fixed64,3,opt,name=max_gap,json=maxGap,proto3" json:"max_gap,omitempty"` // Maximum gap_from_parent observed for this feature
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpanGapBounds) Reset() {
	*x = SpanGapBounds{}
	mi := &file_tpack_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpanGapBounds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpanGapBounds) ProtoMessage() {}

func (x *SpanGapBounds) ProtoReflect() protoreflect.Message {
	mi := &file_tpack_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpanGapBounds.ProtoReflect.Descriptor instead.
func (*SpanGapBounds) Descriptor() ([]byte, []int) {
	return file_tpack_proto_rawDescGZIP(), []int{8}
}

func (x *SpanGapBounds) GetFeature() *NodeFeature {
	if x != nil {
		return x.Feature
	}
	return nil
}

func (x *SpanGapBounds) GetMinGap() float64 {
	if x != nil {
		return x.MinGap
	}
	return 0
}

func (x *SpanGapBounds) GetMaxGap() float64 {
	if x != nil {
		return x.MaxGap
	}
	return 0
}

// Gaussian mixture model parameters
type GaussianMixtureParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weights       []float64              `protobuf:"fixed64,1,rep,packed,name=weights,proto3" json:"weights,omitempty"`                    // Component weights (sum to 1)
	Means         []float64              `protobuf:"fixed64,2,rep,packed,name=means,proto3" json:"means,omitempty"`                        // Component means
	Variances     []float64              `protobuf:"fixed64,3,rep,packed,name=variances,proto3" json:"variances,omitempty"`                // Component variances (for 1D case)
	NComponents   int32                  `protobuf:"varint,4,opt,name=n_components,json=nComponents,proto3" json:"n_components,omitempty"` // Number of components
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GaussianMixtureParams) Reset() {
	*x = GaussianMixtureParams{}
	mi := &file_tpack_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GaussianMixtureParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GaussianMixtureParams) ProtoMessage() {}

func (x *GaussianMixtureParams) ProtoReflect() protoreflect.Message {
	mi := &file_tpack_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GaussianMixtureParams.ProtoReflect.Descriptor instead.
func (*GaussianMixtureParams) Descriptor() ([]byte, []int) {
	return file_tpack_proto_rawDescGZIP(), []int{9}
}

func (x *GaussianMixtureParams) GetWeights() []float64 {
	if x != nil {
		return x.Weights
	}
	return nil
}

func (x *GaussianMixtureParams) GetMeans() []float64 {
	if x != nil {
		return x.Means
	}
	return nil
}

func (x *GaussianMixtureParams) GetVariances() []float64 {
	if x != nil {
		return x.Variances
	}
	return nil
}

func (x *GaussianMixtureParams) GetNComponents() int32 {
	if x != nil {
		return x.NComponents
	}
	return 0
}

// Statistical dependent-attribute model: linear regression per (parent, child) node pair
// Conditions gap_ratio and duration_ratio on log(parentDuration+1) and normalizedChildIdx
type StatisticalDependentAttributeModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentNodeIdx int32                  `protobuf:"varint,1,opt,name=parent_node_idx,json=parentNodeIdx,proto3" json:"parent_node_idx,omitempty"`
	ChildNodeIdx  int32                  `protobuf:"varint,2,opt,name=child_node_idx,json=childNodeIdx,proto3" json:"child_node_idx,omitempty"`
	// Sample count (for weighting/confidence)
	SampleCount int32 `protobuf:"varint,3,opt,name=sample_count,json=sampleCount,proto3" json:"sample_count,omitempty"`
	// Per-column categorical probability distributions (one entry per dependent attribute)
	DependentAttributeProbs []*DependentAttributeProbs `protobuf:"bytes,4,rep,name=dependent_attribute_probs,json=dependentAttributeProbs,proto3" json:"dependent_attribute_probs,omitempty"`
	// Gap regression: gapRatio = gap_beta0 + gap_beta1*logDur + gap_beta2*childIdx + N(0, gap_residual_std)
	GapBeta0       float64 `protobuf:"fixed64,5,opt,name=gap_beta0,json=gapBeta0,proto3" json:"gap_beta0,omitempty"`
	GapBeta1       float64 `protobuf:"fixed64,6,opt,name=gap_beta1,json=gapBeta1,proto3" json:"gap_beta1,omitempty"`
	GapBeta2       float64 `protobuf:"fixed64,7,opt,name=gap_beta2,json=gapBeta2,proto3" json:"gap_beta2,omitempty"`
	GapResidualStd float64 `protobuf:"fixed64,8,opt,name=gap_residual_std,json=gapResidualStd,proto3" json:"gap_residual_std,omitempty"`
	// Duration regression: durRatio = dur_beta0 + dur_beta1*logDur + dur_beta2*childIdx + N(0, dur_residual_std)
	DurBeta0       float64 `protobuf:"fixed64,9,opt,name=dur_beta0,json=durBeta0,proto3" json:"dur_beta0,omitempty"`
	DurBeta1       float64 `protobuf:"fixed64,10,opt,name=dur_beta1,json=durBeta1,proto3" json:"dur_beta1,omitempty"`
	DurBeta2       float64 `protobuf:"fixed64,11,opt,name=dur_beta2,json=durBeta2,proto3" json:"dur_beta2,omitempty"`
	DurResidualStd float64 `protobuf:"fixed64,12,opt,name=dur_residual_std,json=durResidualStd,proto3" json:"dur_residual_std,omitempty"`
	// Percentile fields (used when offset_param = "percentile")
	// 21 values each: p0,p5,p10,...,p95,p100 in absolute µs
	GapPercentiles []float64 `protobuf:"fixed64,13,rep,packed,name=gap_percentiles,json=gapPercentiles,proto3" json:"gap_percentiles,omitempty"`
	DurPercentiles []float64 `protobuf:"fixed64,14,rep,packed,name=dur_percentiles,json=durPercentiles,proto3" json:"dur_percentiles,omitempty"`
	// Memorized raw (gapRatio, durRatio) pairs for small groups (≤20 samples)
	MemorizedGaps []float64 `protobuf:"fixed64,15,rep,packed,name=memorized_gaps,json=memorizedGaps,proto3" json:"memorized_gaps,omitempty"`
	MemorizedDurs []float64 `protobuf:"fixed64,16,rep,packed,name=memorized_durs,json=memorizedDurs,proto3" json:"memorized_durs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatisticalDependentAttributeModel) Reset() {
	*x = StatisticalDependentAttributeModel{}
	mi := &file_tpack_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticalDependentAttributeModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticalDependentAttributeModel) ProtoMessage() {}

func (x *StatisticalDependentAttributeModel) ProtoReflect() protoreflect.Message {
	mi := &file_tpack_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticalDependentAttributeModel.ProtoReflect.Descriptor instead.
func (*StatisticalDependentAttributeModel) Descriptor() ([]byte, []int) {
	return file_tpack_proto_rawDescGZIP(), []int{10}
}

func (x *StatisticalDependentAttributeModel) GetParentNodeIdx() int32 {
	if x != nil {
		return x.ParentNodeIdx
	}
	return 0
}

func (x *StatisticalDependentAttributeModel) GetChildNodeIdx() int32 {
	if x != nil {
		return x.ChildNodeIdx
	}
	return 0
}

func (x *StatisticalDependentAttributeModel) GetSampleCount() int32 {
	if x != nil {
		return x.SampleCount
	}
	return 0
}

func (x *StatisticalDependentAttributeModel) GetDependentAttributeProbs() []*DependentAttributeProbs {
	if x != nil {
		return x.DependentAttributeProbs
	}
	return nil
}

func (x *StatisticalDependentAttributeModel) GetGapBeta0() float64 {
	if x != nil {
		return x.GapBeta0
	}
	return 0
}

func (x *StatisticalDependentAttributeModel) GetGapBeta1() float64 {
	if x != nil {
		return x.GapBeta1
	}
	return 0
}

func (x *StatisticalDependentAttributeModel) GetGapBeta2() float64 {
	if x != nil {
		return x.GapBeta2
	}
	return 0
}

func (x *StatisticalDependentAttributeModel) GetGapResidualStd() float64 {
	if x != nil {
		return x.GapResidualStd
	}
	return 0
}

func (x *StatisticalDependentAttributeModel) GetDurBeta0() float64 {
	if x != nil {
		return x.DurBeta0
	}
	return 0
}

func (x *StatisticalDependentAttributeModel) GetDurBeta1() float64 {
	if x != nil {
		return x.DurBeta1
	}
	return 0
}

func (x *StatisticalDependentAttributeModel) GetDurBeta2() float64 {
	if x != nil {
		return x.DurBeta2
	}
	return 0
}

func (x *StatisticalDependentAttributeModel) GetDurResidualStd() float64 {
	if x != nil {
		return x.DurResidualStd
	}
	return 0
}

func (x *StatisticalDependentAttributeModel) GetGapPercentiles() []float64 {
	if x != nil {
		return x.GapPercentiles
	}
	return nil
}

func (x *StatisticalDependentAttributeModel) GetDurPercentiles() []float64 {
	if x != nil {
		return x.DurPercentiles
	}
	return nil
}

func (x *StatisticalDependentAttributeModel) GetMemorizedGaps() []float64 {
	if x != nil {
		return x.MemorizedGaps
	}
	return nil
}

func (x *StatisticalDependentAttributeModel) GetMemorizedDurs() []float64 {
	if x != nil {
		return x.MemorizedDurs
	}
	return nil
}

// Categorical probabilities for one dependent attribute within a node-pair's stats.
type DependentAttributeProbs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Probs         []float64              `protobuf:"fixed64,1,rep,packed,name=probs,proto3" json:"probs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DependentAttributeProbs) Reset() {
	*x = DependentAttributeProbs{}
	mi := &file_tpack_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DependentAttributeProbs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependentAttributeProbs) ProtoMessage() {}

func (x *DependentAttributeProbs) ProtoReflect() protoreflect.Message {
	mi := &file_tpack_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependentAttributeProbs.ProtoReflect.Descriptor instead.
func (*DependentAttributeProbs) Descriptor() ([]byte, []int) {
	return file_tpack_proto_rawDescGZIP(), []int{11}
}

func (x *DependentAttributeProbs) GetProbs() []float64 {
	if x != nil {
		return x.Probs
	}
	return nil
}

// Trace template: a full tree topology stored as a BFS-ordered node sequence.
// Used when topology_mode = "template" (ablation baseline).
type TraceTemplateProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeFeature         `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`                                                // BFS-ordered nodes, index 0 = root
	ParentIndices []int32                `protobuf:"varint,2,rep,packed,name=parent_indices,json=parentIndices,proto3" json:"parent_indices,omitempty"`   // parent index in nodes array, -1 for root
	Count         uint64                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`                                               // number of traces matching this template
	TraceType     TraceType              `protobuf:"varint,4,opt,name=trace_type,json=traceType,proto3,enum=tpack.TraceType" json:"trace_type,omitempty"` // NORMAL or ERROR
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceTemplateProto) Reset() {
	*x = TraceTemplateProto{}
	mi := &file_tpack_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceTemplateProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceTemplateProto) ProtoMessage() {}

func (x *TraceTemplateProto) ProtoReflect() protoreflect.Message {
	mi := &file_tpack_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceTemplateProto.ProtoReflect.Descriptor instead.
func (*TraceTemplateProto) Descriptor() ([]byte, []int) {
	return file_tpack_proto_rawDescGZIP(), []int{12}
}

func (x *TraceTemplateProto) GetNodes() []*NodeFeature {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *TraceTemplateProto) GetParentIndices() []int32 {
	if x != nil {
		return x.ParentIndices
	}
	return nil
}

func (x *TraceTemplateProto) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *TraceTemplateProto) GetTraceType() TraceType {
	if x != nil {
		return x.TraceType
	}
	return TraceType_NORMAL
}

var File_tpack_proto protoreflect.FileDescriptor

const file_tpack_proto_rawDesc = "" +
	"\n" +
	"\vtpack.proto\x12\x05tpack\"\xfc\a\n" +
	"\vTPackModels\x12'\n" +
	"\x0fnode_vocabulary\x18\x01 \x03(\tR\x0enodeVocabulary\x12*\n" +
	"\x06config\x18\x02 \x01(\v2\x12.tpack.TPackConfigR\x06config\x12)\n" +
	"\x11min_start_time_us\x18\x03 \x01(\x03R\x0eminStartTimeUs\x12)\n" +
	"\x11max_start_time_us\x18\x04 \x01(\x03R\x0emaxStartTimeUs\x12\x1f\n" +
	"\vtrace_count\x18\x05 \x01(\x05R\n" +
	"traceCount\x12&\n" +
	"\x0fmax_nodes_count\x18\x06 \x01(\x05R\rmaxNodesCount\x126\n" +
	"\vroot_models\x18\a \x03(\v2\x15.tpack.RootCountModelR\n" +
	"rootModels\x12=\n" +
	"\x0ftopology_models\x18\b \x03(\v2\x14.tpack.TopologyModelR\x0etopologyModels\x12J\n" +
	"\x14root_duration_models\x18\t \x03(\v2\x18.tpack.RootDurationModelR\x12rootDurationModels\x12K\n" +
	"\x14span_duration_bounds\x18\n" +
	" \x03(\v2\x19.tpack.SpanDurationBoundsR\x12spanDurationBounds\x12<\n" +
	"\x0fspan_gap_bounds\x18\v \x03(\v2\x14.tpack.SpanGapBoundsR\rspanGapBounds\x12s\n" +
	" statistical_dependent_attributes\x18\f \x03(\v2).tpack.StatisticalDependentAttributeModelR\x1estatisticalDependentAttributes\x121\n" +
	"\x14dependent_attributes\x18\r \x03(\tR\x13dependentAttributes\x12\\\n" +
	"\x1adependent_attribute_vocabs\x18\x0e \x03(\v2\x1e.tpack.DependentAttributeVocabR\x18dependentAttributeVocabs\x12-\n" +
	"\x12primary_attributes\x18\x0f \x03(\tR\x11primaryAttributes\x122\n" +
	"\x15cumulative_vocab_size\x18\x10 \x01(\x05R\x13cumulativeVocabSize\x12B\n" +
	"\x0ftrace_templates\x18\x11 \x03(\v2\x19.tpack.TraceTemplateProtoR\x0etraceTemplates\"R\n" +
	"\x17DependentAttributeVocab\x12\x1f\n" +
	"\vcolumn_name\x18\x01 \x01(\tR\n" +
	"columnName\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\"\x90\x04\n" +
	"\vTPackConfig\x12\x1b\n" +
	"\tmax_depth\x18\x01 \x01(\x05R\bmaxDepth\x12!\n" +
	"\fmax_children\x18\x02 \x01(\x05R\vmaxChildren\x12,\n" +
	"\x12max_gmm_components\x18\x03 \x01(\x05R\x10maxGmmComponents\x12-\n" +
	"\x13min_samples_for_gmm\x18\x04 \x01(\x05R\x10minSamplesForGmm\x12?\n" +
	"\x1creject_sampling_max_attempts\x18\x05 \x01(\x05R\x19rejectSamplingMaxAttempts\x126\n" +
	"\x17reject_sampling_enabled\x18\x06 \x01(\bR\x15rejectSamplingEnabled\x12/\n" +
	"\x13stratified_sampling\x18\a \x01(\bR\x12stratifiedSampling\x12\x1f\n" +
	"\vrandom_seed\x18\b \x01(\x05R\n" +
	"randomSeed\x12!\n" +
	"\foffset_value\x18\t \x01(\tR\voffsetValue\x12!\n" +
	"\foffset_model\x18\n" +
	" \x01(\tR\voffsetModel\x12.\n" +
	"\x13use_duration_bounds\x18\v \x01(\bR\x11useDurationBounds\x12#\n" +
	"\rtopology_mode\x18\f \x01(\tR\ftopologyMode\"f\n" +
	"\vNodeFeature\x12\x19\n" +
	"\bnode_idx\x18\x01 \x01(\x05R\anodeIdx\x12\x1b\n" +
	"\tchild_idx\x18\x02 \x01(\x05R\bchildIdx\x12\x1f\n" +
	"\vchild_count\x18\x03 \x01(\x05R\n" +
	"childCount\"\x85\x01\n" +
	"\x0eRootCountModel\x12,\n" +
	"\afeature\x18\x01 \x01(\v2\x12.tpack.NodeFeatureR\afeature\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12/\n" +
	"\n" +
	"trace_type\x18\x03 \x01(\x0e2\x10.tpack.TraceTypeR\ttraceType\"\xca\x01\n" +
	"\rTopologyModel\x129\n" +
	"\x0eparent_feature\x18\x01 \x01(\v2\x12.tpack.NodeFeatureR\rparentFeature\x127\n" +
	"\rchild_feature\x18\x02 \x01(\v2\x12.tpack.NodeFeatureR\fchildFeature\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x04R\x05count\x12/\n" +
	"\n" +
	"trace_type\x18\x04 \x01(\x0e2\x10.tpack.TraceTypeR\ttraceType\"\xc9\x01\n" +
	"\x11RootDurationModel\x12,\n" +
	"\afeature\x18\x01 \x01(\v2\x12.tpack.NodeFeatureR\afeature\x12@\n" +
	"\fdistribution\x18\x02 \x01(\v2\x1c.tpack.GaussianMixtureParamsR\fdistribution\x12!\n" +
	"\fmin_duration\x18\x03 \x01(\x01R\vminDuration\x12!\n" +
	"\fmax_duration\x18\x04 \x01(\x01R\vmaxDuration\"\x88\x01\n" +
	"\x12SpanDurationBounds\x12,\n" +
	"\afeature\x18\x01 \x01(\v2\x12.tpack.NodeFeatureR\afeature\x12!\n" +
	"\fmin_duration\x18\x02 \x01(\x01R\vminDuration\x12!\n" +
	"\fmax_duration\x18\x03 \x01(\x01R\vmaxDuration\"o\n" +
	"\rSpanGapBounds\x12,\n" +
	"\afeature\x18\x01 \x01(\v2\x12.tpack.NodeFeatureR\afeature\x12\x17\n" +
	"\amin_gap\x18\x02 \x01(\x01R\x06minGap\x12\x17\n" +
	"\amax_gap\x18\x03 \x01(\x01R\x06maxGap\"\x88\x01\n" +
	"\x15GaussianMixtureParams\x12\x18\n" +
	"\aweights\x18\x01 \x03(\x01R\aweights\x12\x14\n" +
	"\x05means\x18\x02 \x03(\x01R\x05means\x12\x1c\n" +
	"\tvariances\x18\x03 \x03(\x01R\tvariances\x12!\n" +
	"\fn_components\x18\x04 \x01(\x05R\vnComponents\"\x93\x05\n" +
	"\"StatisticalDependentAttributeModel\x12&\n" +
	"\x0fparent_node_idx\x18\x01 \x01(\x05R\rparentNodeIdx\x12$\n" +
	"\x0echild_node_idx\x18\x02 \x01(\x05R\fchildNodeIdx\x12!\n" +
	"\fsample_count\x18\x03 \x01(\x05R\vsampleCount\x12Z\n" +
	"\x19dependent_attribute_probs\x18\x04 \x03(\v2\x1e.tpack.DependentAttributeProbsR\x17dependentAttributeProbs\x12\x1b\n" +
	"\tgap_beta0\x18\x05 \x01(\x01R\bgapBeta0\x12\x1b\n" +
	"\tgap_beta1\x18\x06 \x01(\x01R\bgapBeta1\x12\x1b\n" +
	"\tgap_beta2\x18\a \x01(\x01R\bgapBeta2\x12(\n" +
	"\x10gap_residual_std\x18\b \x01(\x01R\x0egapResidualStd\x12\x1b\n" +
	"\tdur_beta0\x18\t \x01(\x01R\bdurBeta0\x12\x1b\n" +
	"\tdur_beta1\x18\n" +
	" \x01(\x01R\bdurBeta1\x12\x1b\n" +
	"\tdur_beta2\x18\v \x01(\x01R\bdurBeta2\x12(\n" +
	"\x10dur_residual_std\x18\f \x01(\x01R\x0edurResidualStd\x12'\n" +
	"\x0fgap_percentiles\x18\r \x03(\x01R\x0egapPercentiles\x12'\n" +
	"\x0fdur_percentiles\x18\x0e \x03(\x01R\x0edurPercentiles\x12%\n" +
	"\x0ememorized_gaps\x18\x0f \x03(\x01R\rmemorizedGaps\x12%\n" +
	"\x0ememorized_durs\x18\x10 \x03(\x01R\rmemorizedDurs\"/\n" +
	"\x17DependentAttributeProbs\x12\x14\n" +
	"\x05probs\x18\x01 \x03(\x01R\x05probs\"\xac\x01\n" +
	"\x12TraceTemplateProto\x12(\n" +
	"\x05nodes\x18\x01 \x03(\v2\x12.tpack.NodeFeatureR\x05nodes\x12%\n" +
	"\x0eparent_indices\x18\x02 \x03(\x05R\rparentIndices\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x04R\x05count\x12/\n" +
	"\n" +
	"trace_type\x18\x04 \x01(\x0e2\x10.tpack.TraceTypeR\ttraceType*\"\n" +
	"\tTraceType\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x00\x12\t\n" +
	"\x05ERROR\x10\x01B3Z1github.com/ProjectASAP/TPack/pkg/tpackmodel/protob\x06proto3"

var (
	file_tpack_proto_rawDescOnce sync.Once
	file_tpack_proto_rawDescData []byte
)

func file_tpack_proto_rawDescGZIP() []byte {
	file_tpack_proto_rawDescOnce.Do(func() {
		file_tpack_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tpack_proto_rawDesc), len(file_tpack_proto_rawDesc)))
	})
	return file_tpack_proto_rawDescData
}

var file_tpack_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tpack_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_tpack_proto_goTypes = []any{
	(TraceType)(0),                             // 0: tpack.TraceType
	(*TPackModels)(nil),                        // 1: tpack.TPackModels
	(*DependentAttributeVocab)(nil),            // 2: tpack.DependentAttributeVocab
	(*TPackConfig)(nil),                        // 3: tpack.TPackConfig
	(*NodeFeature)(nil),                        // 4: tpack.NodeFeature
	(*RootCountModel)(nil),                     // 5: tpack.RootCountModel
	(*TopologyModel)(nil),                      // 6: tpack.TopologyModel
	(*RootDurationModel)(nil),                  // 7: tpack.RootDurationModel
	(*SpanDurationBounds)(nil),                 // 8: tpack.SpanDurationBounds
	(*SpanGapBounds)(nil),                      // 9: tpack.SpanGapBounds
	(*GaussianMixtureParams)(nil),              // 10: tpack.GaussianMixtureParams
	(*StatisticalDependentAttributeModel)(nil), // 11: tpack.StatisticalDependentAttributeModel
	(*DependentAttributeProbs)(nil),            // 12: tpack.DependentAttributeProbs
	(*TraceTemplateProto)(nil),                 // 13: tpack.TraceTemplateProto
}
var file_tpack_proto_depIdxs = []int32{
	3,  // 0: tpack.TPackModels.config:type_name -> tpack.TPackConfig
	5,  // 1: tpack.TPackModels.root_models:type_name -> tpack.RootCountModel
	6,  // 2: tpack.TPackModels.topology_models:type_name -> tpack.TopologyModel
	7,  // 3: tpack.TPackModels.root_duration_models:type_name -> tpack.RootDurationModel
	8,  // 4: tpack.TPackModels.span_duration_bounds:type_name -> tpack.SpanDurationBounds
	9,  // 5: tpack.TPackModels.span_gap_bounds:type_name -> tpack.SpanGapBounds
	11, // 6: tpack.TPackModels.statistical_dependent_attributes:type_name -> tpack.StatisticalDependentAttributeModel
	2,  // 7: tpack.TPackModels.dependent_attribute_vocabs:type_name -> tpack.DependentAttributeVocab
	13, // 8: tpack.TPackModels.trace_templates:type_name -> tpack.TraceTemplateProto
	4,  // 9: tpack.RootCountModel.feature:type_name -> tpack.NodeFeature
	0,  // 10: tpack.RootCountModel.trace_type:type_name -> tpack.TraceType
	4,  // 11: tpack.TopologyModel.parent_feature:type_name -> tpack.NodeFeature
	4,  // 12: tpack.TopologyModel.child_feature:type_name -> tpack.NodeFeature
	0,  // 13: tpack.TopologyModel.trace_type:type_name -> tpack.TraceType
	4,  // 14: tpack.RootDurationModel.feature:type_name -> tpack.NodeFeature
	10, // 15: tpack.RootDurationModel.distribution:type_name -> tpack.GaussianMixtureParams
	4,  // 16: tpack.SpanDurationBounds.feature:type_name -> tpack.NodeFeature
	4,  // 17: tpack.SpanGapBounds.feature:type_name -> tpack.NodeFeature
	12, // 18: tpack.StatisticalDependentAttributeModel.dependent_attribute_probs:type_name -> tpack.DependentAttributeProbs
	4,  // 19: tpack.TraceTemplateProto.nodes:type_name -> tpack.NodeFeature
	0,  // 20: tpack.TraceTemplateProto.trace_type:type_name -> tpack.TraceType
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_tpack_proto_init() }
func file_tpack_proto_init() {
	if File_tpack_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tpack_proto_rawDesc), len(file_tpack_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tpack_proto_goTypes,
		DependencyIndexes: file_tpack_proto_depIdxs,
		EnumInfos:         file_tpack_proto_enumTypes,
		MessageInfos:      file_tpack_proto_msgTypes,
	}.Build()
	File_tpack_proto = out.File
	file_tpack_proto_goTypes = nil
	file_tpack_proto_depIdxs = nil
}
