name: tpack_otel_demo_no_status_code
primary_attributes:
- service.name
- span.kind
- operation.name
- http.status_code
- server.address
- server.port
- rpc.method
- rpc.service
- next.span_name
- peer.address
- next.span_signature
- rpc.system
- rpc.grpc.status_code
- http.method
- http.target
- upstream_cluster
- upstream_cluster.name
- component
- response_flags
- http.protocol
- net.peer.name
dependent_attributes:
- http.url
- net.peer.port
- status.code
metadata_predictor: statistical
offset_value: ratio
offset_model: regression
