name: tpack_gmm4
primary_attributes:
  - service.name
  - operation.name
  - status.code
  - grpc.status
metadata_predictor: statistical
offset_value: ratio
offset_model: regression
max_gmm_components: 4
